<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="results.xsl"?>
<DebugReport SchemaVersion="1.0"><Header><Data id="Time" name="Time">Wednesday, February 27, 2019 7:55:19 PM</Data><Data id="RunningAsAdmin" name="Running As Admin">false</Data><ComputerInformation name="USE-PC"><Data id="Version" name="Windows Version">6.1</Data><Data id="SKU" name="SKU">Client</Data><Data id="Architecture" name="Architecture">amd64</Data></ComputerInformation><PackageInformation id="NetworkDiagnostics" name="Windows Network Diagnostics"><Data id="Version" name="Package Version">1.0</Data><Data id="Publisher" name="Publisher">Microsoft Windows</Data><Data id="Description" name="Description">Detects problems with network connectivity.</Data></PackageInformation></Header><Scripts><Script name="NetworkDiagnosticsTroubleshoot.ps1"><Data id="RunningTime" name="Running Time">343</Data><Parameters/><DetailedInformation><Detail id="SecurityBoundarySafe" name="Security Boundary Safe" verbosity="Debug"><Data id="Description" name="Description"></Data><Contents><Objects><Object Type="System.String">SBS Data Retrieved: C010AF26-7754-410B-ADF6-24B6B35D8EC1:0</Object></Objects></Contents></Detail><Detail id="ReuseSession" name="Reusing previous session" verbosity="Debug"><Data id="Description" name="Description"></Data><Contents><Objects><Object Type="System.String">Previous run's privilege level flag (0) matches our current level (IsAdmin:False). Determining whether it's appropriate to re-run.</Object></Objects></Contents></Detail><Detail id="OpenExistingSessionFailure" name="Open Existing Session" verbosity="Debug"><Data id="Description" name="Description">Failed while opening existing NDF session.</Data><Contents><Objects><Object Type="System.String">Exception: System.Reflection.TargetInvocationException Message: Exception has been thrown by the target of an invocation.</Object></Objects></Contents></Detail><Detail id="ScriptException" name="Script Error" verbosity="Debug"><Data id="Description" name="Description">An error written by a cmdlet into the PowerShell error stream</Data><Contents><ScriptException>System.Management.Automation.RuntimeException: Could not open re-run incident.
   at System.Management.Automation.FlowControlNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.ParseTreeNode.Execute(Array input, Pipe outputPipe, ArrayList&amp; resultList, ExecutionContext context)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputPipe, ArrayList&amp; resultList, ExecutionContext context)</ScriptException></Contents></Detail></DetailedInformation></Script></Scripts><Functions><Function id="Initialize" name="Initialize"><Data id="RunningTime" name="Running Time">265</Data><Data id="StatusCode" name="Status Code">0x0</Data><InputArguments><Data id="PackagePath" name="Path to Package">C:\Windows\diagnostics\system\Networking</Data><Data id="Client" name="Callback Pointer">0x00000000003E75C0</Data><Data id="Answer" name="Interaction Responses">&lt;Answers xmlns="http://www.microsoft.com/schemas/dcm/configuration/2008" Version="1.0"&gt;
	&lt;Interaction ID="IT_EntryPoint"&gt;
		&lt;Value&gt;Inbound&lt;/Value&gt;
	&lt;/Interaction&gt;
&lt;/Answers&gt;</Data></InputArguments><OutputArguments/></Function><Function id="Diagnose" name="Diagnose"><Data id="RunningTime" name="Running Time">702</Data><Data id="StatusCode" name="Status Code">0x803C0101</Data><InputArguments/><OutputArguments><Data id="Result" name="Results"></Data></OutputArguments></Function></Functions></DebugReport>
